services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - 80

  backend:
    build: ./backend
    container_name: backend
    expose:
      - 5000
    environment:
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}