name: CI/CD pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd backend
          pytest -v
        env:
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: build frontend image
        run: docker build -t weather-frontend ./frontend

      - name: build backend image
        run: docker build -t weather-backend ./backend

      - name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to docker hub
        run: |
          docker tag weather-frontend mosakr1/weather-frontend:latest
          docker tag weather-backend mosakr1/weather-backend:latest
          docker push mosakr1/weather-frontend:latest
          docker push mosakr1/weather-backend:latest